//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package ti.exame.soap;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ti.exame.soap package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ti.exame.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetPetsByOwnerResponse }
     * 
     * @return
     *     the new instance of {@link GetPetsByOwnerResponse }
     */
    public GetPetsByOwnerResponse createGetPetsByOwnerResponse() {
        return new GetPetsByOwnerResponse();
    }

    /**
     * Create an instance of {@link GetPetsByOwnerRequest }
     * 
     * @return
     *     the new instance of {@link GetPetsByOwnerRequest }
     */
    public GetPetsByOwnerRequest createGetPetsByOwnerRequest() {
        return new GetPetsByOwnerRequest();
    }

    /**
     * Create an instance of {@link GetPetsByOwnerResponse.Pet }
     * 
     * @return
     *     the new instance of {@link GetPetsByOwnerResponse.Pet }
     */
    public GetPetsByOwnerResponse.Pet createGetPetsByOwnerResponsePet() {
        return new GetPetsByOwnerResponse.Pet();
    }

}
